# Use an official Go runtime as the base image
FROM golang:alpine

# adds gcc
RUN apk add build-base

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download Go module dependencies
RUN go mod download

# Copy the Go source code
COPY . .

# Build the Go application
RUN go build -o app

# Set the environment variables
ENV PORT=8080

# Expose the container port
EXPOSE 8080

# Run the Go application
CMD ["./app"]
